import "./globals.css"
import type { Metadata } from "next"
import { Header } from "@/components/Header"
import { Montserrat } from "next/font/google"

const montserrat= Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Header/>
        <main className="max-w-[100rem] mx-auto">
          {children}
        </main>
      </body>
    </html>
  )
}