import "./globals.css";
import type { Metadata } from "next";
import { Header } from "../components/Header";
import { Montserrat } from "next/font/google";
import ClientWrapper from "./ClientWrapper";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sky Netics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`scroll-smooth antialiased bg-gray-50/80 ${montserrat.variable}`}>
        <Header />
        <main className="w-full">
          <ClientWrapper>{children}</ClientWrapper>
        </main>
      </body>
    </html>
  );
}
